{{- if and .Values.server.enabled .Values.rbac.create (ne .Values.newrelic.scrape_case "just_nodes") .Values.newrelic.namespaces -}}
{{ range $.Values.newrelic.namespaces }}
---
apiVersion: {{ template "rbac.apiVersion" $ }}
kind: RoleBinding
metadata:
  labels:
    {{- include "prometheus.server.labels" $ | nindent 4 }}
  name: {{ template "prometheus.server.fullname" $ }}
  namespace: {{ . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "prometheus.serviceAccountName.server" $ }}
{{ include "prometheus.namespace" $ | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "prometheus.server.fullname" $ }}
{{- end }}
{{- end }}
